# Generated by Django 3.1.14 on 2022-11-12 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
    ]

    operations = [
        migrations.CreateModel(
            name='NadpisSFonomPluginSetting',
            fields=[
                ('cmsplugin_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='plugins_nadpissfonompluginsetting', serialize=False, to='cms.cmsplugin')),
                ('nadpis', models.CharField(max_length=255, verbose_name='Надпись')),
                ('fon', models.ImageField(upload_to='', verbose_name='Фон')),
                ('visota', models.CharField(default='100px', max_length=255, verbose_name='Высота')),
            ],
            options={
                'verbose_name': 'HTML вставка',
                'verbose_name_plural': 'HTML вставка',
            },
            bases=('cms.cmsplugin',),
        ),
    ]
