# Generated by Django 3.1.14 on 2022-11-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadpissfonompluginsetting',
            name='visota',
            field=models.IntegerField(default=100, verbose_name='Высота'),
        ),
    ]
